# coding: utf-8
# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = '3c6830e7960ed7aa8e590777da567b5b'
  config.secret_key = 'd289d0234577fba0373903cd457bb254'
  config.default_from = 'remi50avJ.C@live.fr'
  # Mailjet API v3.1 is at the moment limited to Send API.
  # We’ve not set the version to it directly since there is no other endpoint in that version.
  # We recommend you create a dedicated instance of the wrapper set with it to send your emails.
  # If you're only using the gem to send emails, then you can safely set it to this version.
  # Otherwise, you can remove the dedicated line into config/initializers/mailjet.rb.
  config.api_version = 'v3.1'
end
